baseURL = "https://example.org/"
title = "The Lee Post"
paginate = 6
defaultContentLanguage = "ko"

[taxonomies]
  tag = "tags"
  category = "categories"

[menus]
  [[menus.main]]
    name = "Home"
    pageRef = "/"
    weight = 1

  [[menus.main]]
    name = "About"
    pageRef = "/about"
    weight = 2

  [[menus.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "/posts"
    weight = 3
    
      [[menus.main]]
        name = "Project"
        url = "/categories/project"
        parent = "posts"
        weight = 1

      [[menus.main]]
        name = "Machine Learning"
        url = "/categories/machine-learning"
        parent = "posts"
        weight = 2
      
      [[menus.main]]
        name = "Reinforcement Learning"
        url = "/categories/reinforcement-learning"
        parent = "posts"
        weight = 3

      [[menus.main]]
        name = "Photograph"
        url = "/categories/photograph"
        parent = "posts"
        weight = 4

  [[menus.main]]
    name = "Gallery"
    pageRef = "/gallery"
    weight = 4

  [[menus.main]]
    name = "Hugo"
    url = "https://gohugo.io/"
    post = '<i class="bi bi-arrow-up-right-square"></i>'
    weight = 5
    [menus.main.params]
      external = true
      

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

defaultContentLanguageInSubdir = true
[languages]
  [languages.ko]
    contentDir = "content/ko"
    staticDir = "static"
    disabled = false
    languageCode = "ko-KR"
    languageDirection = "ltr"
    languageName = "Korean"
  [languages.en]
    contentDir = "content/en"
    staticDir = "static"
    disabled = false
    languageCode = "en-US"
    languageDirection = "ltr"
    languageName = "English"

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true